server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848  #修改本机的host文件
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service_router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: member-service_router
          uri: lb://member-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: test_router
          uri: https://www.baidu.com
          predicates:
            - Path=/test/**
          filters:           #不加，nacos就无法路由到指定位置
            - StripPrefix=1
    sentinel:
      transport:
        dashboard: sentinel-server:8858
      datasource:
#        ds1.file:
#          file: classpath:gw-flow.json
#          ruleType: gw_flow
        ds1.nacos:
          serverAddr: nacos-server:8848
          dataId: gw-flow
          ruleType: gw_flow
#        ds2.file:
#          file: classpath:api-group.json
#          ruleType: gw_api_group
        ds2.nacos:
          serverAddr: nacos-server:8848
          dataId: api-group
          ruleType: gw_api_group

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456